version: '3.4'

services:
  backend:
    build:
      context: Backend/AnimalRescue
      dockerfile: Dockerfile
    container_name: animalrescue.backend
    image: animalrescue.api
    restart: unless-stopped
    ports:
      - "9595:80"
    environment:
      - AdminDetail__Email=admin@animalrescue.com
      - AdminDetail__Password=TestPassword123#
      - AppSettings__JwtExpireHours=1
      - AppSettings__JwtExpireDays=30
      - AppSettings__JwtIssuer=http://localhost:9595/
      - AppSettings__JwtAudience=localhost
      - AppSettings__JwtKey=SOME_RANDOM_KEY_DO_NOT_SHARE
      - AppSettings__FrontEndUrl=http://localhost:9090/
      - Smtp__Host=smtp.gmail.com
      - Smtp__Port=587
      - Smtp__UseSsl=true
      - Smtp__DisplayName=Animal Rescue
      - Smtp__Email=anuitexmail@gmail.com
      - Smtp__Username=anuitexmail@gmail.com
      - Smtp__Password=Qwe123!2020
      - MongoDbSettings__ConnectionString=mongodb://mongodbuser:mongodbpass@mongodb:27017
      - MongoDbSettings__DatabaseName=animal_rescue
      - MongoDbSettings__BucketName=file_records
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Debug
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Debug
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - frontend
      - backend

  portal:
    build:
      context: Frontend
      dockerfile: Dockerfile
    container_name: animalrescue.portal
    image: animalrescue.portal
    restart: unless-stopped
    ports:
      - "9090:80"
    environment:
      - API_URL=http://localhost:9595/api/
      - YOUTUBE_URL=https://www.googleapis.com/youtube/v3/
      - YOUTUBE_API_KEY=youtubeapikeyhere
      - YOUTUBE_CHANNEL_ID=youtubechannelidhere
    networks:
      - frontend

  mongodb:
    container_name: "mongodb"
    image: mongo:4.2
    restart: unless-stopped
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=animal_rescue
      - MONGO_INITDB_ROOT_USERNAME=mongodbuser
      - MONGO_INITDB_ROOT_PASSWORD=mongodbpass
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  rabbitmq:
    image: 'bitnami/rabbitmq:3.8.3'
    networks:
      - backend

volumes:
  mongodbdata:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge 